# DEV environment setting#
#---------------------------
  
# Database ---------------- Postgres
spring:
  datasource:    
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5430/orderms    
    username: githubuser
    password: '{cipher}e54d4f03e0976f0c7f2d94b2abc5a8659a902299901607fc3ca126a345ded471'
  #Hibernate
  jpa:
    #Hibernate
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    generate-ddl: true
    show-sql: false
    
# Actuator allow all for dev
management:
  endpoints:
    web:
      exposure:
        include: "*"
