eureka:
  client:
    service-url:
      defaultZone: http://localhost:2525/eureka
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    baseurl: http://localhost:9411